version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
      time: "08:00"
      day: "saturday"
      timezone: "Europe/Berlin"
  - package-ecosystem: 'bundler'
    directory: '/'
    schedule:
      interval: 'weekly'
      time: "08:00"
      day: "sunday"
      timezone: "Europe/Berlin"